# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [20.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test

  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Copy Repository to Remote Server
      uses: appleboy/scp-action@master
      with:
        host: 15.206.78.9
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./
        target: /home/ec2-user/github-actions-first-flight/

    - name: Start the application on remote Server
      uses: appleboy/ssh-action@master
      with:
        host: 15.206.78.9
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd /home/ec2-user/github-actions-first-flight/
            git pull origin main
            npm install
            sudo pm2 delete GithubActions-app
            sudo pm2 start server.js --name GithubActions-app
            sudo pm2 save
            sudo pm2 startup
            sudo pm2 restart GithubActions-app